FROM python:3.8-slim-buster

RUN apt-get update && apt-get install -y \
	build-essential \
	gcc \
	make \
	python3-scipy

# clean
RUN apt-get clean \
	&& apt-get autoclean \
	&& rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN pip install boto3 PyMySQL python-dateutil pytz
